[project]
name = "simple_autoclicker"
version = "0.1.0"
description = "A simple mouse autoclicker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
]
